spring:
  profiles:
    group:
      "local": "console-logging,http-console-logging"
      "dev": "file-logging,http-file-logging,console-logging,http-console-logging"
      "prod": "file-logging,http-file-logging"
    include: slack-logging
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
jwt:
  header: token
  issuer: ahpuh
  client-secret: ${JWT_CLIENT_SECRET}
  expiry-seconds: 2592000
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
