spring:
  application:
    name: surf
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/surf;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
jwt:
  header: token
  issuer: ahpuh
  client-secret: ${JWT-CLIENT-SECRET}
  expiry-seconds: 2592000